require("dotenv").config();
const port = process.env.APP_PORT;
const express = require("express");
const app = express();
const movieControllers = require("./controllers/movieControllers");
const userControllers = require("./controllers/userControllers");
app.use(express.json());
app.get("/api/movies", movieControllers.getMovies);
app.get("/api/movies/:id", movieControllers.getMovieById);
app.get("/api/users", userControllers.getUsers);
app.get("/api/users/:id", userControllers.getUserById);
app.post("/api/movies", movieControllers.postMovie);
app.post("/api/users", userControllers.postUsers);
app.put("/api/movies/:id", movieControllers.updateMovie);
module.exports = app;
